import numpy as np
x=[1,2,3,4,5]
type(x)
print(type(x))
arr=np.array(x)

print(arr)
print(type(arr))
print(type(arr))
arr=np.arange(1,13)
print(arr)
arr=np.arange(1,13,3)
print(arr)
arr=np.zeros((2,4))
print(arr)
arr=np.ones((2,4))
print(arr)
np.random.seed(0)
arr1=np.random.randint(10,1000,50)
arr1=arr1.reshape(5,10)
print(arr1)